# Generated by Django 3.2.8 on 2022-03-21 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
