# Generated by Django 3.2.8 on 2022-03-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_alter_access_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(),
        ),
    ]
