# Generated by Django 3.2.8 on 2022-05-09 19:02

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_auto_20220502_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
