# Generated by Django 3.2.8 on 2022-05-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_alter_training_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='description',
        ),
    ]
