# Generated by Django 3.2.8 on 2022-05-09 19:09

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_remove_training_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
