# Generated by Django 4.0.3 on 2022-05-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_training_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='media-file/'),
        ),
    ]
