# Generated by Django 4.0.3 on 2022-05-20 14:37

from django.db import migrations, models
import webapp.storages


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_uploadprivate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(storage=webapp.storages.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(storage=webapp.storages.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='module',
            name='thumbnail',
            field=models.ImageField(storage=webapp.storages.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='training',
            name='thumbnail',
            field=models.ImageField(storage=webapp.storages.PrivateMediaStorage(), upload_to=''),
        ),
    ]
