# Generated by Django 4.0.3 on 2022-05-21 02:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0043_phone_and_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phone_and_address',
            new_name='Contact_Info',
        ),
    ]
